version: "3.9"

# Variables passed to the containers
networks:
  ulp-network:
    name: ulp-network

volumes:
  uwsgi-data:
  web-static:
  ulp-data:
  ulp-webapp:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/ulp-database/ulp-webapp
      o: bind

services:
  postgres:
    hostname: ${DBHOST}
    container_name: postgres
    build: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_DB: ${DBNAME}
    networks:
      - ulp-network
    volumes:
      - ulp-data:/var/lib/postgresql/data

  django:
    hostname: django
    container_name: django
    build: ulp-webapp
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBHOST: ${DBHOST}
      DBPORT: ${DBPORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      WAN_IP: ${WAN_IP}
      ULP_URL: ${ULP_URL}
    networks:
      - ulp-network
    volumes:
      - uwsgi-data:/tmp/uwsgi
      - web-static:/ulp-webapp/ulp-webapp/static
      - web-static:/var/www/ulp-webapp/static
      - ulp-webapp:/ulp-webapp

  nginx:
   hostname: nginx
   container_name: nginx
   image: nginx:latest
   restart: always
   networks:
     - ulp-network
   volumes:
     - uwsgi-data:/tmp/uwsgi/
     - ulp-webapp:/ulp-webapp
     - ./nginx/conf/:/etc/nginx/conf.d/:ro
     - ./certbot/www/:/var/www/certbot/:ro
     - ./certbot/conf/:/etc/nginx/ssl/:ro
   ports:
     - "80:80"
     - "443:443"
   depends_on:
     - django

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

