version: "3.9"

# Variables passed to the containers
networks:
  ulp-network:
    name: ulp-network

services:
  postgres:
    hostname: ${DBHOST}
    container_name: postgres
    build: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_DB: ${DBNAME}
    networks:
      - ulp-network

