version: "3.9"

# Variables passed to the containers
networks:
  ulp-network:
    name: ulp-network

volumes:
  ulp-data:

services:
  postgres:
    hostname: ${DBHOST}
    container_name: postgres
    build: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DBPASS}
      PGDATA: ${DBDATA}
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBHOST: ${DBHOST}
      DBPORT: ${DBPORT}
    networks:
      - ulp-network
    volumes:
      - ulp-data:${DBDATA}

  django:
    hostname: django
    container_name: django
    build: ulp-webapp
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBHOST: ${DBHOST}
      DBPORT: ${DBPORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    networks:
      - ulp-network

# nginx:
#   hostname: nginx
#   container_name: nginx
#   build: nginx
#   restart: always
#   networks:
#     - ulp-network
#   volumes:
#     - uwsgi_data:/tmp/uwsgi/
#   ports:
#     - "80:80"
#   depends_on:
#     - django
