# Generated by Django 5.0.2 on 2024-02-08 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citet_text', models.CharField(blank=True, help_text='The display text when this is cited inline, e.g., Smith et. al (1900)', max_length=127, null=True)),
                ('doi', models.CharField(blank=True, help_text='The DOI of the article', max_length=1023, null=True, verbose_name='DOI')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the parameter', max_length=63, unique=True)),
                ('description', models.TextField(blank=True, help_text='A description of this measurable parameter', null=True)),
                ('ascii_symbol', models.CharField(help_text='The symbol used for this parameter, expressed in ASCII characters', max_length=15)),
                ('latex_symbol', models.CharField(blank=True, help_text='The symbol used for this parameter, expressed as a LaTeX expression', max_length=63, null=True)),
                ('unit', models.CharField(blank=True, help_text="The (astropy-conversant) unit of this parameter (e.g. 's', 'lightyear')", max_length=31, null=True)),
                ('prefer_scientific_notation', models.BooleanField(default=False, help_text='True: 3x10²; False: 300')),
            ],
        ),
        migrations.AddField(
            model_name='ulp',
            name='abbr',
            field=models.CharField(blank=True, help_text='A short version of the name', max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=20, help_text='The numerical value of this measurement', max_digits=40)),
                ('power_of_10', models.IntegerField(default=0, help_text='The true quantity is multiplied by this power of 10. Same with the errors.')),
                ('err', models.DecimalField(blank=True, decimal_places=20, help_text='The (symmetrical) uncertainty on the quantity', max_digits=40, null=True)),
                ('err_hi', models.DecimalField(blank=True, decimal_places=20, help_text='The (asymmetrical) upper uncertainty on the quantity', max_digits=40, null=True)),
                ('err_lo', models.DecimalField(blank=True, decimal_places=20, help_text='The (asymmetrical) lower uncertainty on the quantity', max_digits=40, null=True)),
                ('error_is_range', models.BooleanField(default=False, help_text="Display the error as a range, e.g. '1 - 5' instead of '3 ± 2'")),
                ('approximation', models.BooleanField(default=False, help_text='Display the error as a approximation, with the ~ symbol')),
                ('date', models.DateTimeField(blank=True, help_text='The date/time when this measurement was made', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any extra notes on this measurement', null=True)),
                ('prefer_scientific_notation', models.BooleanField(default=False, help_text='True: 3x10²; False: 300')),
                ('article', models.ForeignKey(help_text='The article in which this measurement is published', on_delete=django.db.models.deletion.RESTRICT, related_name='measurements', to='published.article')),
                ('ulp', models.ForeignKey(help_text='The ULP for to which this measurement applies', on_delete=django.db.models.deletion.RESTRICT, related_name='measurements', to='published.ulp')),
                ('parameter', models.ForeignKey(help_text='The parameter beaing measured', on_delete=django.db.models.deletion.RESTRICT, related_name='measurements', to='published.parameter')),
            ],
        ),
    ]
