# Generated by Django 4.2.6 on 2024-02-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('published', '0003_ulp_discoverer_ulp_editors_ulp_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='ulp',
            field=models.ForeignKey(help_text='The ULP for to which this measurement applies', on_delete=django.db.models.deletion.RESTRICT, related_name='measurements', to='published.ulp', verbose_name='ULP'),
        ),
    ]
