# Generated by Django 4.2.6 on 2024-02-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0006_measurement_lower_limit_measurement_sigfig_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={"ordering": ["ulp", "article", "parameter"]},
        ),
        migrations.CreateModel(
            name="ParameterSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name for the parameter set (e.g. 'ephemeris', 'main table', 'viewing geometry')",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "parameters",
                    models.ManyToManyField(
                        blank=True, related_name="sets", to="published.parameter"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
