# Generated by Django 5.0.2 on 2024-02-09 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0009_rename_unit_parameter_astropy_unit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="access",
            field=models.CharField(
                choices=[("P", "Public"), ("G", "Group"), ("O", "Only me")],
                default="O",
                help_text="If published, everyone can access. If unpublished, this setting chooses who can see this measurement.",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who made this measurement, if not a published measurement",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="made_measurements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
