# Generated by Django 5.0.2 on 2024-02-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("published", "0011_rename_sigfig_measurement_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="access_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which groups can view this measurement",
                related_name="measurements",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="precision",
            field=models.IntegerField(
                blank=True,
                help_text="The number of decimal places to display",
                null=True,
            ),
        ),
    ]
