# Generated by Django 5.0.2 on 2024-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published', '0012_measurement_access_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='freq_astropy_units',
            field=models.CharField(default='MHz', help_text='An astropy-conversant unit string that applies to the frequencies.', max_length=31),
        ),
        migrations.AddField(
            model_name='measurement',
            name='freq_ctr',
            field=models.FloatField(blank=True, help_text='The centre frequency at which this measurement was made.', null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='freq_hi',
            field=models.FloatField(blank=True, help_text='The top of the frequency range at which this measurement was made.', null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='freq_lo',
            field=models.FloatField(blank=True, help_text='The bottom of the frequency range at which this measurement was made.', null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='notes',
            field=models.TextField(blank=True, help_text='Extra notes about this measurement.', null=True),
        ),
    ]
