# Generated by Django 5.0.2 on 2024-02-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0022_alter_measurement_err_alter_measurement_err_hi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="error_sigma",
            field=models.FloatField(
                default=1,
                help_text="The sigma of the reported errors.",
                verbose_name="Error significance, σ",
            ),
        ),
    ]
