# Generated by Django 5.0.2 on 2024-02-11 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('published', '0024_measurement_stokes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulp',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='ulp',
            name='readers',
        ),
    ]
