# Generated by Django 5.0.2 on 2024-03-21 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='bw',
            field=models.FloatField(help_text='The bandwidth.', verbose_name='Bandwidth'),
        ),
        migrations.AlterField(
            model_name='backend',
            name='freq_ctr',
            field=models.FloatField(help_text='The centre frequency of the band.', verbose_name='Centre frequency'),
        ),
        migrations.AlterField(
            model_name='backend',
            name='telescope',
            field=models.ForeignKey(help_text='The telescope to which this backend belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='backends', to='data.telescope'),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='abbr',
            field=models.CharField(blank=True, help_text='The abbreviation of the name.', max_length=15, null=True, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='latitude_deg',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='The latitude (in degrees) of the telescope.', max_digits=14, null=True, verbose_name='Latitude (°)'),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='longitude_deg',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='The longitude (in degrees) of the telescope.', max_digits=14, null=True, verbose_name='Longitude (°)'),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='name',
            field=models.CharField(help_text='The name of the telescope.', max_length=255, unique=True),
        ),
    ]
