# Generated by Django 5.0.2 on 2024-03-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_backend_bw_alter_backend_freq_ctr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='bw',
            field=models.FloatField(blank=True, help_text='The bandwidth.', null=True, verbose_name='Bandwidth'),
        ),
        migrations.AlterField(
            model_name='backend',
            name='freq_ctr',
            field=models.FloatField(blank=True, help_text='The centre frequency of the band.', null=True, verbose_name='Centre frequency'),
        ),
        migrations.AlterField(
            model_name='backend',
            name='freq_units',
            field=models.CharField(blank=True, default='MHz', help_text='An astropy-conversant unit string that applies to the frequencies.', max_length=31, null=True),
        ),
    ]
