# Generated by Django 5.0.2 on 2024-03-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_backend_bw_alter_backend_freq_ctr_and_more'),
        ('published', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOfArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjd', models.DecimalField(decimal_places=20, help_text='The MJD of the time of arrival.', max_digits=30, verbose_name='MJD')),
                ('mjd_err', models.DecimalField(blank=True, decimal_places=20, help_text='The 1σ uncertainty of the time of arrival (in days).', max_digits=30, null=True, verbose_name='MJD error')),
                ('barycentred', models.BooleanField(default=True, help_text='Whether this TOA has been barycentred.')),
                ('dedispersed', models.BooleanField(default=True, help_text='Whether this TOA has been corrected for dedispersion.')),
                ('ulp', models.ForeignKey(help_text='The associated ULP.', on_delete=django.db.models.deletion.CASCADE, related_name='times_of_arrival', to='published.ulp', verbose_name='ULP')),
            ],
            options={
                'ordering': ['ulp', 'mjd'],
            },
        ),
    ]
