# Generated by Django 5.0.2 on 2024-03-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_timeofarrival'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeofarrival',
            options={'ordering': ['ulp', 'mjd'], 'verbose_name_plural': 'Times of arrival'},
        ),
    ]
