# Generated by Django 5.0.2 on 2024-03-23 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0005_alter_timeofarrival_options"),
        ("published", "0002_ulp_data_access_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="EphemerisParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tempo_name",
                    models.CharField(
                        help_text="The name of this parameter according to TEMPO.",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "tempo_astropy_units",
                    models.CharField(
                        help_text="The (astropy-conversant) unit if this parameter that TEMPO uses. The unit must be dimensionally equivalent to that of the matching parameter.",
                        max_length=31,
                    ),
                ),
                (
                    "parameter",
                    models.OneToOneField(
                        help_text="The parameter type.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ephemeris_parameter",
                        to="published.parameter",
                    ),
                ),
            ],
            options={
                "ordering": ["tempo_name"],
            },
        ),
    ]
