# Generated by Django 5.0.2 on 2024-03-23 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_ephemerisparameter"),
        ("published", "0002_ulp_data_access_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="EphemerisMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ephemeris_parameter",
                    models.ForeignKey(
                        help_text="The associated parameter of this measurement.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ephemeris_measurements",
                        to="data.ephemerisparameter",
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        help_text="The measurement itself.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ephemeris_measurements",
                        to="published.measurement",
                    ),
                ),
            ],
            options={
                "ordering": ["measurement__ulp", "ephemeris_parameter"],
            },
        ),
    ]
