# Generated by Django 5.0.8 on 2024-09-25 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_ephemerismeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofarrival',
            name='backend',
            field=models.ForeignKey(blank=True, help_text='The telescope backend that made this detection.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='toas', to='data.backend'),
        ),
        migrations.AddField(
            model_name='timeofarrival',
            name='raw_mjd',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='The MJD of the time of arrival, before barycentring or dedispersing.', max_digits=30, null=True, verbose_name='Raw MJD'),
        ),
        migrations.AlterField(
            model_name='timeofarrival',
            name='mjd',
            field=models.DecimalField(decimal_places=20, help_text='The barycentered MJD of the time of arrival.', max_digits=30, verbose_name='MJD'),
        ),
    ]
