# Generated by Django 5.0.8 on 2024-09-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_timeofarrival_backend_timeofarrival_raw_mjd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofarrival',
            name='freq',
            field=models.FloatField(blank=True, help_text='The centre frequency of this detection in MHz.', null=True),
        ),
        migrations.AddField(
            model_name='timeofarrival',
            name='freq_units',
            field=models.CharField(blank=True, default='MHz', help_text='An astropy-conversant unit string that applies to the frequency.', max_length=31, null=True),
        ),
    ]
