# Generated by Django 5.0.2 on 2024-07-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_timeofarrival_telescope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeofarrival',
            old_name='mjd_err',
            new_name='toa_err',
        ),
    ]
