# Generated by Django 5.0.8 on 2024-09-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_timeofarrival_freq_timeofarrival_freq_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofarrival',
            name='notes',
            field=models.TextField(blank=True, help_text='Any extra information about the ToA, its measurement method, or the pulse in general.', null=True),
        ),
        migrations.AddField(
            model_name='timeofarrival',
            name='peak_flux_Jy',
            field=models.FloatField(blank=True, help_text='The peak flux of the pulse in Jy.', null=True),
        ),
        migrations.AddField(
            model_name='timeofarrival',
            name='pulse_width',
            field=models.FloatField(blank=True, help_text='The width of the pulse in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='timeofarrival',
            name='upper_limit',
            field=models.BooleanField(default=False, help_text='Whether the given peak flux is an upper limit (thereby signifying that this ToA is a "non-detection").'),
        ),
    ]
