# Generated by Django 5.0.2 on 2024-07-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_mjd_err_timeofarrival_toa_err'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofarrival',
            name='toa_err_units',
            field=models.CharField(default='day', help_text='An astropy.units-readable unit', max_length=31),
        ),
        migrations.AlterField(
            model_name='timeofarrival',
            name='toa_err',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='The 1σ uncertainty of the time of arrival', max_digits=30, null=True, verbose_name='TOA error'),
        ),
    ]
