# Generated by Django 5.0.8 on 2024-09-26 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_timeofarrival_notes_timeofarrival_peak_flux_jy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofarrival',
            name='telescope',
            field=models.ForeignKey(blank=True, help_text='The telescope that made this detection.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='toas', to='data.telescope'),
        ),
    ]
