# Generated by Django 5.0.2 on 2024-07-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_timeofarrival_freq_timeofarrival_freq_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeofarrival',
            name='freq',
            field=models.FloatField(blank=True, help_text='The frequency at which the TOA was detected', null=True, verbose_name='Centre frequency'),
        ),
        migrations.AlterField(
            model_name='timeofarrival',
            name='freq_units',
            field=models.CharField(default='MHz', help_text='An astropy.units-readable unit that applies to the "Frequency" field', max_length=31, verbose_name='Centre frequency units'),
        ),
        migrations.AlterField(
            model_name='timeofarrival',
            name='toa_err_units',
            field=models.CharField(default='day', help_text='An astropy.units-readable unit that applies to the "TOA err" field', max_length=31, verbose_name='TOA error units'),
        ),
    ]
