# Generated by Django 5.0.8 on 2024-09-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_timeofarrival_telescope'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofarrival',
            name='bw',
            field=models.FloatField(blank=True, help_text='The bandwidth of this detection.', null=True, verbose_name='Bandwidth'),
        ),
        migrations.AddField(
            model_name='timeofarrival',
            name='rotation_measure',
            field=models.FloatField(blank=True, help_text='The rotation measure of this detection in rad/m^2.', null=True),
        ),
        migrations.AddField(
            model_name='timeofarrival',
            name='spectral_index',
            field=models.FloatField(blank=True, help_text='The spectral index of this detection.', null=True),
        ),
        migrations.AlterField(
            model_name='timeofarrival',
            name='freq',
            field=models.FloatField(blank=True, help_text='The centre frequency of this detection.', null=True, verbose_name='Frequency'),
        ),
    ]
