# Generated by Django 5.0.8 on 2024-09-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0013_plot_timeofarrival_plots"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeofarrival",
            name="telescope_name",
            field=models.CharField(
                blank=True,
                help_text="The telescope that made this detection. Must match a string in AstroPy's EarthLocation.get_site_names().",
                max_length=255,
                null=True,
            ),
        ),
    ]
