# Generated by Django 5.0.8 on 2024-09-28 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("data", "0015_timeofarrival_can_edit_groups_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeofarrival",
            name="freq_units",
        ),
        migrations.AlterField(
            model_name="timeofarrival",
            name="can_edit_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups that are granted edit privileges. All groups with edit privileges can also view.",
                related_name="%(app_label)s_%(class)s_as_editor",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="timeofarrival",
            name="can_edit_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users that are granted edit privileges. All users with edit privileges can also view.",
                related_name="%(app_label)s_%(class)s_as_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
