# Generated by Django 5.0.8 on 2024-09-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_alter_timeofarrival_freq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeofarrival",
            name="backend",
        ),
        migrations.RemoveField(
            model_name="timeofarrival",
            name="telescope",
        ),
        migrations.DeleteModel(
            name="Backend",
        ),
        migrations.DeleteModel(
            name="Telescope",
        ),
    ]
