# Generated by Django 5.0.8 on 2024-09-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0019_lightcurve_timeofarrival_lightcurve_lightcurvepoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lightcurve",
            name="dm_freq",
            field=models.FloatField(
                blank=True,
                help_text="The reference frequency used when dedispersing, in MHz. Leaving this field blank has a special meaning: it is equivalent to setting the reference frequency to (+ve) infinity.",
                null=True,
            ),
        ),
    ]
