# Generated by Django 5.0.8 on 2024-09-29 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0020_lightcurve_dm_freq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lightcurve",
            name="pol",
        ),
        migrations.RemoveField(
            model_name="timeofarrival",
            name="lightcurve",
        ),
        migrations.AddField(
            model_name="timeofarrival",
            name="lcI",
            field=models.ForeignKey(
                blank=True,
                help_text="The Stokes I lightcurve from which this ToA was derived.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="toas_as_I",
                to="data.lightcurve",
                verbose_name="Lightcurve (I)",
            ),
        ),
        migrations.AddField(
            model_name="timeofarrival",
            name="lcQ",
            field=models.ForeignKey(
                blank=True,
                help_text="The Stokes Q lightcurve from which this ToA was derived.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="toas_as_Q",
                to="data.lightcurve",
                verbose_name="Lightcurve (Q)",
            ),
        ),
        migrations.AddField(
            model_name="timeofarrival",
            name="lcU",
            field=models.ForeignKey(
                blank=True,
                help_text="The Stokes U lightcurve from which this ToA was derived.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="toas_as_U",
                to="data.lightcurve",
                verbose_name="Lightcurve (U)",
            ),
        ),
        migrations.AddField(
            model_name="timeofarrival",
            name="lcV",
            field=models.ForeignKey(
                blank=True,
                help_text="The Stokes V lightcurve from which this ToA was derived.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="toas_as_V",
                to="data.lightcurve",
                verbose_name="Lightcurve (V)",
            ),
        ),
    ]
