# Generated by Django 5.0.8 on 2024-09-29 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0021_remove_lightcurve_pol_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeofarrival",
            name="lcI",
        ),
        migrations.RemoveField(
            model_name="timeofarrival",
            name="lcQ",
        ),
        migrations.RemoveField(
            model_name="timeofarrival",
            name="lcU",
        ),
        migrations.RemoveField(
            model_name="timeofarrival",
            name="lcV",
        ),
        migrations.AddField(
            model_name="lightcurvepoint",
            name="pol",
            field=models.CharField(
                choices=[
                    ("I", "Stokes I"),
                    ("Q", "Stokes Q"),
                    ("U", "Stokes U"),
                    ("V", "Stokes V"),
                ],
                default="I",
                help_text="The polarisation of this point.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="timeofarrival",
            name="lightcurve",
            field=models.ForeignKey(
                blank=True,
                help_text="The lightcurve from which this ToA was derived.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="toas",
                to="data.lightcurve",
            ),
        ),
    ]
