# Generated by Django 5.0.8 on 2024-09-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0022_remove_timeofarrival_lci_remove_timeofarrival_lcq_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lightcurvepoint",
            name="pol",
            field=models.CharField(
                default="I", help_text="The polarisation of this point.", max_length=15
            ),
        ),
    ]
