# Generated by Django 5.0.8 on 2024-09-30 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('data', '0024_lightcurve_telescope'),
        ('published', '0003_ulp_whitelist_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingEphemeris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pepoch', models.FloatField(blank=True, help_text='The reference epoch for period measurement (MJD)', null=True)),
                ('p0', models.FloatField(blank=True, help_text='The period at time "pepoch" (s)', null=True)),
                ('p1', models.FloatField(blank=True, help_text='The period derivative at time "pepoch" (s/s)', null=True)),
                ('pb', models.FloatField(blank=True, help_text='The orbital period (h)', null=True)),
                ('can_edit_groups', models.ManyToManyField(blank=True, help_text='Groups that are granted edit privileges. All groups with edit privileges can also view.', related_name='%(app_label)s_%(class)s_as_editor', to='auth.group')),
                ('can_edit_users', models.ManyToManyField(blank=True, help_text='Users that are granted edit privileges. All users with edit privileges can also view.', related_name='%(app_label)s_%(class)s_as_editor', to=settings.AUTH_USER_MODEL)),
                ('can_view_groups', models.ManyToManyField(blank=True, help_text='Groups that are granted view privileges.', related_name='%(app_label)s_%(class)s_as_viewer', to='auth.group')),
                ('can_view_users', models.ManyToManyField(blank=True, help_text='Users that are granted view privileges.', related_name='%(app_label)s_%(class)s_as_viewer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='The owner of this instance.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_as_owner', to=settings.AUTH_USER_MODEL)),
                ('ulp', models.ForeignKey(help_text='The source this ephemeris applies to', on_delete=django.db.models.deletion.CASCADE, related_name='working_ephemerides', to='published.ulp')),
            ],
            options={
                'verbose_name_plural': 'Working ephemerides',
            },
        ),
        migrations.AddConstraint(
            model_name='workingephemeris',
            constraint=models.UniqueConstraint(fields=('owner', 'ulp'), name='working_ephemeris_ulp_owner_unique'),
        ),
    ]
