# Generated by Django 5.0.8 on 2024-09-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_workingephemeris_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingephemeris',
            name='dm',
            field=models.FloatField(blank=True, help_text='The dispersion measure (pc/cm^3)', null=True),
        ),
    ]
