# Generated by Django 5.0.8 on 2024-10-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_remove_workingephemeris_peak_value_jy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingephemeris',
            old_name='siB',
            new_name='spec_alpha',
        ),
        migrations.RenameField(
            model_name='workingephemeris',
            old_name='siC',
            new_name='spec_q',
        ),
        migrations.RenameField(
            model_name='workingephemeris',
            old_name='siA',
            new_name='spec_s1GHz',
        ),
    ]
