# Generated by Django 5.0.8 on 2024-10-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_rename_sib_workingephemeris_spec_alpha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingephemeris',
            name='spec_alpha',
            field=models.FloatField(blank=True, help_text="The spectral index. The 'alpha' in the equation S = S1GHz * f^alpha * exp(q*ln(f)^2), where f is the frequency in GHz and S is in Jy.", null=True),
        ),
        migrations.AlterField(
            model_name='workingephemeris',
            name='spec_q',
            field=models.FloatField(blank=True, help_text="The 'q' in the equation S = S1GHz * f^alpha * exp(q*ln(f)^2), where f is the frequency in GHz and S is in Jy", null=True),
        ),
        migrations.AlterField(
            model_name='workingephemeris',
            name='spec_s1GHz',
            field=models.FloatField(blank=True, help_text="The flux density (Jy) at 1 GHz. The 'S1GHz' in the equation S = S1GHz * f^alpha * exp(q*ln(f)^2), where f is the frequency in GHz and S is in Jy.", null=True),
        ),
    ]
