# Generated by Django 5.0.8 on 2024-10-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0032_alter_workingephemeris_spec_alpha_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workingephemeris",
            name="spec_s1GHz",
        ),
    ]
