# Generated by Django 5.0.8 on 2024-10-04 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0033_remove_workingephemeris_spec_s1ghz"),
    ]

    operations = [
        migrations.AddField(
            model_name="lightcurve",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lightcurve",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
