# Generated by Django 5.0.8 on 2024-10-04 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0034_lightcurve_created_lightcurve_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulse",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pulse",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="workingephemeris",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workingephemeris",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
