# Generated by Django 5.0.8 on 2024-10-04 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("data", "0035_pulse_created_pulse_updated_workingephemeris_created_and_more"),
        ("published", "0003_ulp_whitelist_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "can_edit_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups that are granted edit privileges. All groups with edit privileges can also view.",
                        related_name="%(app_label)s_%(class)s_as_editor",
                        to="auth.group",
                    ),
                ),
                (
                    "can_edit_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users that are granted edit privileges. All users with edit privileges can also view.",
                        related_name="%(app_label)s_%(class)s_as_editor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "can_view_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups that are granted view privileges.",
                        related_name="%(app_label)s_%(class)s_as_viewer",
                        to="auth.group",
                    ),
                ),
                (
                    "can_view_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users that are granted view privileges.",
                        related_name="%(app_label)s_%(class)s_as_viewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The owner of this instance.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_as_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ulp",
                    models.ForeignKey(
                        help_text="The source this template applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="published.ulp",
                    ),
                ),
            ],
            options={
                "ordering": ["ulp", "updated"],
            },
        ),
        migrations.CreateModel(
            name="TemplateComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("A", models.FloatField()),
                ("mu", models.FloatField(help_text="In units of pulse phase.")),
                ("sigma", models.FloatField(help_text="In units of pulse phase.")),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The template to which this component belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="data.template",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplatePulse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pulse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.pulse"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.template"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="template",
            name="included_pulses",
            field=models.ManyToManyField(
                related_name="templates",
                through="data.TemplatePulse",
                to="data.template",
            ),
        ),
        migrations.CreateModel(
            name="Toa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "pulse_number",
                    models.IntegerField(
                        help_text="The pulse number as derived from the linked working ephemeris."
                    ),
                ),
                (
                    "toa_mjd",
                    models.DecimalField(
                        decimal_places=20,
                        help_text="The barycentered MJD of the ToA.",
                        max_digits=30,
                        verbose_name="ToA (MJD)",
                    ),
                ),
                (
                    "toa_err_s",
                    models.DecimalField(
                        decimal_places=20,
                        help_text="The 1σ uncertainty of the time of arrival (in seconds).",
                        max_digits=30,
                        verbose_name="ToA error (s)",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The template used to derive this ToA.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toas",
                        to="data.template",
                    ),
                ),
                (
                    "working_ephemeris",
                    models.ForeignKey(
                        help_text="The working ephemeris used to derive this ToA.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toas",
                        to="data.workingephemeris",
                    ),
                ),
            ],
            options={
                "verbose_name": "ToA",
                "verbose_name_plural": "ToAs",
                "ordering": ["template", "pulse_number"],
            },
        ),
    ]
