# Generated by Django 5.0.8 on 2024-10-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0036_template_templatecomponent_templatepulse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="included_pulses",
            field=models.ManyToManyField(
                related_name="templates", through="data.TemplatePulse", to="data.pulse"
            ),
        ),
    ]
