# Generated by Django 5.0.8 on 2024-10-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0037_alter_template_included_pulses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="templatecomponent",
            old_name="A",
            new_name="weight",
        ),
    ]
