# Generated by Django 5.0.8 on 2024-10-05 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0038_rename_a_templatecomponent_weight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="template",
            options={"ordering": ["working_ephemeris", "updated"]},
        ),
        migrations.RemoveField(
            model_name="template",
            name="ulp",
        ),
        migrations.AddField(
            model_name="template",
            name="working_ephemeris",
            field=models.ForeignKey(
                default=1,
                help_text="The ephemeris used for constructing this template.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="data.workingephemeris",
            ),
            preserve_default=False,
        ),
    ]
