# Generated by Django 5.0.8 on 2024-10-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0039_alter_template_options_remove_template_ulp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toa",
            name="working_ephemeris",
        ),
        migrations.AddField(
            model_name="toa",
            name="ampl",
            field=models.FloatField(
                default=1,
                help_text="The amplitude of the fitted template that matched the data scaled to 'ampl_ref_freq'.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="toa",
            name="ampl_err",
            field=models.FloatField(
                default=1, help_text="The uncertainaty of the amplitude."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="toa",
            name="ampl_ref_freq",
            field=models.FloatField(
                default=1000,
                help_text="The reference frequency used (when scaling the data) to derive the amplitude.",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="toa",
            constraint=models.UniqueConstraint(
                fields=("template", "pulse_number"),
                name="unique_toa_per_pulse_and_template",
            ),
        ),
    ]
