# Generated by Django 5.0.8 on 2024-11-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0041_alter_toa_options_alter_toa_toa_err_s"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingEphemerisCovariance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pepoch_pepoch", models.FloatField(blank=True, null=True)),
                ("pepoch_p0", models.FloatField(blank=True, null=True)),
                ("pepoch_p1", models.FloatField(blank=True, null=True)),
                ("pepoch_pb", models.FloatField(blank=True, null=True)),
                ("pepoch_dm", models.FloatField(blank=True, null=True)),
                ("pepoch_spec_alpha", models.FloatField(blank=True, null=True)),
                ("pepoch_spec_q", models.FloatField(blank=True, null=True)),
                ("p0_p0", models.FloatField(blank=True, null=True)),
                ("p0_p1", models.FloatField(blank=True, null=True)),
                ("p0_pb", models.FloatField(blank=True, null=True)),
                ("p0_dm", models.FloatField(blank=True, null=True)),
                ("p0_spec_alpha", models.FloatField(blank=True, null=True)),
                ("p0_spec_q", models.FloatField(blank=True, null=True)),
                ("p1_p1", models.FloatField(blank=True, null=True)),
                ("p1_pb", models.FloatField(blank=True, null=True)),
                ("p1_dm", models.FloatField(blank=True, null=True)),
                ("p1_spec_alpha", models.FloatField(blank=True, null=True)),
                ("p1_spec_q", models.FloatField(blank=True, null=True)),
                ("pb_pb", models.FloatField(blank=True, null=True)),
                ("pb_dm", models.FloatField(blank=True, null=True)),
                ("pb_spec_alpha", models.FloatField(blank=True, null=True)),
                ("pb_spec_q", models.FloatField(blank=True, null=True)),
                ("dm_dm", models.FloatField(blank=True, null=True)),
                ("dm_spec_alpha", models.FloatField(blank=True, null=True)),
                ("dm_spec_q", models.FloatField(blank=True, null=True)),
                ("spec_alpha_spec_alpha", models.FloatField(blank=True, null=True)),
                ("spec_alpha_spec_q", models.FloatField(blank=True, null=True)),
                ("spec_q_spec_q", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="toa",
            options={
                "ordering": ["pulse_number"],
                "verbose_name": "ToA",
                "verbose_name_plural": "ToAs",
            },
        ),
        migrations.AddField(
            model_name="workingephemeris",
            name="covariance",
            field=models.OneToOneField(
                blank=True,
                help_text="The covariance matrix for the ephemeris parameters",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.workingephemeriscovariance",
            ),
        ),
    ]
