# Generated by Django 5.0.8 on 2024-11-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_workingephemeriscovariance_alter_toa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toa',
            name='baseline_level',
            field=models.FloatField(blank=True, help_text='The baseline level fitted to the lightcurve.', null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='baseline_slope',
            field=models.FloatField(blank=True, help_text='The baseline slope fitted to the lightcurve.', null=True),
        ),
    ]
