# Generated by Django 5.0.8 on 2024-11-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_toa_include_in_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingephemeris',
            name='covariance',
            field=models.OneToOneField(blank=True, help_text='The covariance matrix for the ephemeris parameters', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.workingephemeriscovariance'),
        ),
    ]
