# Generated by Django 5.0.10 on 2024-12-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_alter_workingephemeris_covariance'),
    ]

    operations = [
        migrations.AddField(
            model_name='toa',
            name='toa_freq_MHz',
            field=models.FloatField(blank=True, help_text='The frequency to be used for this ToA.', null=True, verbose_name='Frequency (MHz)'),
        ),
    ]
