# Generated by Django 5.0.10 on 2024-12-10 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_toa_toa_freq_mhz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeofarrival',
            name='lightcurve',
        ),
        migrations.RemoveField(
            model_name='timeofarrival',
            name='pulse',
        ),
        migrations.AddField(
            model_name='toa',
            name='pulse',
            field=models.ForeignKey(blank=True, help_text='The pulse being fitted to.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='toas', to='data.pulse'),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='mjd_end',
            field=models.FloatField(help_text='The (topocentric,not-dedispersed) MJD defining the end of the pulse'),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='mjd_start',
            field=models.FloatField(help_text='The (topocentric, not-dedispersed) MJD defining the start of the pulse'),
        ),
    ]
