# Generated by Django 5.0.10 on 2024-12-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_remove_timeofarrival_lightcurve_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='toa',
            name='unique_toa_per_pulse_and_template',
        ),
        migrations.AlterField(
            model_name='toa',
            name='toa_mjd',
            field=models.DecimalField(decimal_places=20, help_text='The barycentered (and not dedispersed) MJD of the ToA.', max_digits=30, verbose_name='ToA (MJD)'),
        ),
    ]
