# Generated by Django 5.0.10 on 2024-12-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_remove_toa_unique_toa_per_pulse_and_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toa',
            options={'ordering': ['toa_mjd'], 'verbose_name': 'ToA', 'verbose_name_plural': 'ToAs'},
        ),
        migrations.RemoveField(
            model_name='toa',
            name='pulse_number',
        ),
    ]
