# Generated by Django 5.0.10 on 2024-12-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_alter_toa_options_remove_toa_pulse_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecomponent',
            name='mu',
            field=models.FloatField(help_text='In units of days.'),
        ),
        migrations.AlterField(
            model_name='templatecomponent',
            name='sigma',
            field=models.FloatField(help_text='In units of days (must be > 0).'),
        ),
    ]
