# Generated by Django 5.0.10 on 2024-12-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_alter_templatecomponent_mu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toa',
            name='baseline_level',
            field=models.FloatField(blank=True, help_text='The baseline level fitted to the lightcurve (in units of Jy).', null=True),
        ),
        migrations.AlterField(
            model_name='toa',
            name='baseline_slope',
            field=models.FloatField(blank=True, help_text='The baseline slope fitted to the lightcurve (in units of Jy/day).', null=True),
        ),
    ]
