# Generated by Django 5.0.11 on 2025-02-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingephemeris',
            name='dec',
            field=models.CharField(blank=True, help_text='The declination (±DD:MM:SS.S)', max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='workingephemeris',
            name='ra',
            field=models.CharField(blank=True, help_text='The right ascension (HH:MM:SS.S)', max_length=31, null=True),
        ),
    ]
