# Generated by Django 5.1.6 on 2025-03-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0056_observation_can_edit_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="obsid",
            field=models.CharField(
                blank=True,
                help_text="Observation ID",
                max_length=255,
                null=True,
                verbose_name="ObsID",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="pointing_decj_deg",
            field=models.FloatField(
                blank=True,
                help_text="The declination (J2000) of the pointing centre, in deg.",
                null=True,
                verbose_name="Dec (J2000) (°)",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="pointing_raj_deg",
            field=models.FloatField(
                blank=True,
                help_text="The right ascension (J2000) of the pointing centre, in deg.",
                null=True,
                verbose_name="RA (J2000) (°)",
            ),
        ),
    ]
