# Generated by Django 5.0.11 on 2025-03-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_nondetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofarrival',
            name='fluence_Jy_s',
            field=models.FloatField(blank=True, help_text='The fluence of the pulse in Jy s.', null=True),
        ),
    ]
