# Generated by Django 5.0.11 on 2025-07-19 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_timeofarrival_fluence_jy_s'),
        ('published', '0005_alter_usersetting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='published_in',
            field=models.ForeignKey(blank=True, help_text='The article this object is published in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_as_published_in', to='published.article'),
        ),
        migrations.AddField(
            model_name='observation',
            name='published_in',
            field=models.ForeignKey(blank=True, help_text='The article this object is published in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_as_published_in', to='published.article'),
        ),
        migrations.AddField(
            model_name='template',
            name='published_in',
            field=models.ForeignKey(blank=True, help_text='The article this object is published in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_as_published_in', to='published.article'),
        ),
        migrations.AddField(
            model_name='timeofarrival',
            name='published_in',
            field=models.ForeignKey(blank=True, help_text='The article this object is published in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_as_published_in', to='published.article'),
        ),
        migrations.AddField(
            model_name='workingephemeris',
            name='published_in',
            field=models.ForeignKey(blank=True, help_text='The article this object is published in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_as_published_in', to='published.article'),
        ),
    ]
