# Generated by Django 5.1.6 on 2025-09-22 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_lightcurve_published_in_observation_published_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingephemeris',
            name='duration_aw',
            field=models.FloatField(blank=True, help_text='The activity window duration (h)', null=True, verbose_name='Activity window duration'),
        ),
        migrations.AddField(
            model_name='workingephemeris',
            name='p_aw',
            field=models.FloatField(blank=True, help_text='The activity window period (h)', null=True, verbose_name='Activity window period'),
        ),
        migrations.AddField(
            model_name='workingephemeris',
            name='t0_aw',
            field=models.FloatField(blank=True, help_text='The activity window reference epoch (MJD)', null=True, verbose_name='Activity window epoch'),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='telescope',
            field=models.CharField(blank=True, help_text='The telescope that made this observation.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='telescope_name',
            field=models.CharField(blank=True, help_text='The telescope that made this observation.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timeofarrival',
            name='telescope_name',
            field=models.CharField(blank=True, help_text='The telescope that made this detection.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workingephemeris',
            name='covariance',
            field=models.OneToOneField(blank=True, help_text='The covariance matrix for the ephemeris parameters', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_ephemeris', to='data.workingephemeriscovariance'),
        ),
    ]
