# Generated by Django 5.0.2 on 2024-06-27 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published', '0002_ulp_data_access_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ulp',
            name='whitelist_users',
            field=models.ManyToManyField(blank=True, help_text="Any individual users that are given explicit access to this ULP's data.", related_name='data_accessible_ulps', to=settings.AUTH_USER_MODEL),
        ),
    ]
