# Generated by Django 4.2.6 on 2024-02-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0004_alter_measurement_ulp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="article",
            field=models.ForeignKey(
                blank=True,
                help_text="The article in which this measurement is published",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="measurements",
                to="published.article",
            ),
        ),
    ]
