# Generated by Django 5.0.11 on 2025-07-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published', '0005_alter_usersetting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='eph_url',
            field=models.CharField(blank=True, help_text='URL for where the ephemeris in this paper are published.', max_length=1023, null=True, verbose_name='URL for ephemeris'),
        ),
        migrations.AddField(
            model_name='article',
            name='toa_url',
            field=models.CharField(blank=True, help_text='URL for where ToAs in this paper are published.', max_length=1023, null=True, verbose_name='URL for ToAs'),
        ),
    ]
