# Generated by Django 4.2.6 on 2024-02-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0005_alter_measurement_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="lower_limit",
            field=models.BooleanField(
                default=False, help_text="Is this an lower limit?"
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="sigfig",
            field=models.IntegerField(
                blank=True,
                help_text="The number of significant figures to display",
                null=True,
                verbose_name="Significant figures",
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="upper_limit",
            field=models.BooleanField(
                default=False, help_text="Is this an upper limit?"
            ),
        ),
    ]
