# Generated by Django 5.1.6 on 2025-08-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published', '0006_article_eph_url_article_toa_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progenitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('abbr', models.CharField(blank=True, max_length=31, null=True, verbose_name='Abbreviation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='citet_text',
            field=models.CharField(blank=True, help_text='The display text when this is cited inline, e.g., Smith et al. (1900)', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='angle_display',
            field=models.CharField(blank=True, choices=[('D', 'DDMMSS'), ('H', 'HHMMSS'), ('S', 'Harvard spectral classification')], help_text='Display in the chosen format.', max_length=1, null=True, verbose_name='Display format'),
        ),
        migrations.CreateModel(
            name='ProgenitorClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentative', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progenitor_claims', to='published.article')),
                ('progenitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='published.progenitor')),
                ('ulp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progenitor_claims', to='published.ulp')),
            ],
            options={
                'ordering': ['ulp', 'progenitor'],
                'constraints': [models.UniqueConstraint(fields=('ulp', 'progenitor', 'article'), name='unique_ulp_progenitor_article')],
            },
        ),
    ]
