# Generated by Django 5.1.6 on 2025-08-09 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("published", "0007_progenitor_alter_article_citet_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequencyBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, unique=True)),
                ("symbol", models.CharField(max_length=15)),
                ("lo", models.FloatField()),
                ("hi", models.FloatField()),
                (
                    "unit",
                    models.CharField(
                        help_text="astropy.unit-conformant unit in units of either length (for wavelength) or inverse time (for frequency). Applies to 'lo' and 'hi' fields.",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="measurement",
            options={"ordering": ["ulp", "parameter", "article"]},
        ),
        migrations.AddField(
            model_name="measurement",
            name="freq_band",
            field=models.ForeignKey(
                blank=True,
                help_text="The frequency band.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="measurements",
                to="published.frequencyband",
            ),
        ),
    ]
