# Generated by Django 4.2.6 on 2024-02-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0007_alter_measurement_options_parameterset"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameterset",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A helpful description of the parameter set",
                null=True,
            ),
        ),
    ]
