# Generated by Django 5.1.6 on 2025-08-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("published", "0008_frequencyband_alter_measurement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frequencyband",
            name="hi",
            field=models.FloatField(help_text="High end of frequency range (GHz)."),
        ),
        migrations.AlterField(
            model_name="frequencyband",
            name="lo",
            field=models.FloatField(help_text="Low end of frequency range (GHz)."),
        ),
        migrations.AlterField(
            model_name="frequencyband",
            name="unit",
            field=models.CharField(
                help_text="Display unit. AstroPy.unit-conformant unit in units of either length (for wavelength) or inverse time (for frequency).",
                max_length=15,
            ),
        ),
    ]
