# Generated by Django 5.1.6 on 2025-08-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("published", "0009_alter_frequencyband_hi_alter_frequencyband_lo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="frequencyband",
            options={"ordering": ["lo", "hi"]},
        ),
        migrations.AlterField(
            model_name="measurement",
            name="error_sigma",
            field=models.FloatField(
                blank=True,
                help_text="The sigma of the reported errors.",
                null=True,
                verbose_name="Error significance, σ",
            ),
        ),
    ]
