# Generated by Django 5.1.6 on 2025-08-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("published", "0010_alter_frequencyband_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="error_sigma_type",
            field=models.CharField(
                choices=[("%", "%"), ("σ", "σ")],
                default="%",
                help_text="The type of the 'error_sigma' field",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="error_sigma",
            field=models.FloatField(
                blank=True,
                help_text="The confidence of the reported errors.",
                null=True,
                verbose_name="Error confidence",
            ),
        ),
    ]
