# Generated by Django 5.1.6 on 2025-08-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("published", "0011_measurement_error_sigma_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={"ordering": ["quantity", "ulp", "parameter", "article"]},
        ),
        migrations.AddField(
            model_name="measurement",
            name="body",
            field=models.CharField(
                blank=True,
                choices=[("1", "Primary"), ("2", "Secondary"), ("3", "Tertiary")],
                help_text="If system contains more than one stellar body, which body this measurement pertains to.",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="error_sigma_type",
            field=models.CharField(
                choices=[("%", "%"), ("σ", "σ")],
                default="σ",
                help_text="The type of the 'error_sigma' field",
                max_length=2,
                verbose_name="Error confidence type",
            ),
        ),
    ]
