# Generated by Django 5.0.11 on 2025-08-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published', '0012_alter_measurement_options_measurement_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='angle_display',
            new_name='special_display',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='body',
            field=models.CharField(blank=True, choices=[('T', 'Total'), ('1', 'Primary'), ('2', 'Secondary'), ('3', 'Tertiary')], help_text='If system contains more than one stellar body, which body or bodies this measurement pertains to.', max_length=2, null=True),
        ),
    ]
