# Generated by Django 5.0.2 on 2024-02-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0014_alter_article_options_alter_parameter_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The title of the paper",
                max_length=1023,
                null=True,
            ),
        ),
    ]
