# Generated by Django 5.0.2 on 2024-02-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0015_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="chisq",
            field=models.FloatField(
                blank=True,
                help_text="The chi-squared of the fit.",
                null=True,
                verbose_name="χ²",
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="reduced_chisq",
            field=models.FloatField(
                blank=True,
                help_text="The reduced chi-squared of the fit.",
                null=True,
                verbose_name="Reduced χ²",
            ),
        ),
    ]
