# Generated by Django 5.0.2 on 2024-02-10 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0016_measurement_chisq_measurement_reduced_chisq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Covariance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("covariance", models.FloatField(help_text="The covariance value.")),
                (
                    "measurement1",
                    models.ForeignKey(
                        help_text="The first measurement in the pair.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covariances_as_primary",
                        to="published.measurement",
                    ),
                ),
                (
                    "measurement2",
                    models.ForeignKey(
                        help_text="The second measurement in the pair.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covariances_as_secondary",
                        to="published.measurement",
                    ),
                ),
            ],
            options={
                "ordering": ["measurement1", "measurement2"],
            },
        ),
    ]
