# Generated by Django 5.0.2 on 2024-02-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0019_alter_measurement_angle_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="angle_display",
            field=models.CharField(
                choices=[("N", "None"), ("D", "DDMMSS"), ("H", "HHMMSS")],
                default="N",
                help_text="If an angle, display in the chosen sexagesimal format.",
                max_length=1,
            ),
        ),
    ]
