# Generated by Django 5.0.2 on 2024-02-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0020_alter_measurement_angle_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="angle_display",
            field=models.CharField(
                blank=True,
                choices=[("D", "DDMMSS"), ("H", "HHMMSS")],
                help_text="If an angle, display in the chosen sexagesimal format.",
                max_length=1,
                null=True,
            ),
        ),
    ]
