# Generated by Django 5.0.2 on 2024-02-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("published", "0021_alter_measurement_angle_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="err",
            field=models.DecimalField(
                blank=True,
                decimal_places=20,
                help_text="The (symmetrical) uncertainty on the quantity.",
                max_digits=40,
                null=True,
                verbose_name="Error (±)",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="err_hi",
            field=models.DecimalField(
                blank=True,
                decimal_places=20,
                help_text="The (asymmetrical) upper uncertainty on the quantity.",
                max_digits=40,
                null=True,
                verbose_name="Error high (+)",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="err_lo",
            field=models.DecimalField(
                blank=True,
                decimal_places=20,
                help_text="The (asymmetrical) lower uncertainty on the quantity.",
                max_digits=40,
                null=True,
                verbose_name="Error low (-)",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="freq_ctr",
            field=models.FloatField(
                blank=True, help_text="The centre frequency.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="freq_hi",
            field=models.FloatField(
                blank=True, help_text="The top of the frequency range.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="freq_lo",
            field=models.FloatField(
                blank=True, help_text="The bottom of the frequency range.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="power_of_10",
            field=models.IntegerField(default=0, verbose_name="× 10^"),
        ),
    ]
