# Generated by Django 5.0.2 on 2024-02-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published', '0023_measurement_error_sigma'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='stokes',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('Q', 'Q'), ('U', 'U'), ('V', 'V')], help_text='The Stokes parameter associated with this measurement.', max_length=2, null=True),
        ),
    ]
